import { all, get, run } from '../db/d1/core.js';
import { hasPermission, isAdmin, isOwner, getAdminRecord, getAdminsFullRecords, setAdminRole } from '../db/d1/admins.js';
import { getPendingContributionsCount, getReviewableContributionsList, approveContribution, rejectContribution } from '../db/d1/contributions.js';
import { aiUsageStats, aiRegistryGetAll } from '../db/d1/aiRegistry.js';
import { adminHasScopes, folderInAdminScope, getAdminScopes } from '../db/d1/scopes.js';
import { PERMISSION_KEYS, PERMISSION_LABELS, ROLE_LABELS, ROLE_PERMISSION_PRESETS, permissionsToString } from '../constants.js';
const kb=rows=>({inline_keyboard:rows});const btn=(text,callback_data)=>({text,callback_data});
const home=[[btn('🏠 الرئيسية','home')]];
export async function buildWorkerAdmin(db,user){const id=Number(user.id);if(!(await isAdmin(db,id)))return {text:'🔒 هذه المنطقة مخصصة للمشرفين المعتمدين فقط.',reply_markup:kb(home)};const rows=[];const pending=await getPendingContributionsCount(db);if(await hasPermission(db,id,'can_contributions'))rows.push([btn('📥 مراجعة المساهمات'+(pending?' ('+pending+')':''),'admin_pending')]);if(await hasPermission(db,id,'can_ai'))rows.push([btn('🤖 سجل الذكاء الاصطناعي','admin_ai')]);if(await hasPermission(db,id,'can_admins'))rows.push([btn('👥 إدارة المشرفين','admin_admins')]);if(await isOwner(db,id))rows.push([btn('🔐 إدارة الأسرار','admin_secrets')]);rows.push([btn('🧰 أدوات الإدارة','admin_surfaces')]);rows.push([btn('📊 حالة التشغيل','admin_runtime'),btn('🏠 الرئيسية','home')]);return {text:'🛠 <b>إدارة المنصة</b>\n\nاختر الإجراء الذي تريد تنفيذه:',reply_markup:kb(rows)};}
async function canReviewFolder(db,userId,folderId){if(!(await hasPermission(db,userId,'can_contributions')))return false;return !(await adminHasScopes(db,userId)) || await folderInAdminScope(db,userId,folderId);}
export async function buildWorkerPending(db,user){if(!(await hasPermission(db,user.id,'can_contributions')))return {text:'🔒 غير مصرح.',reply_markup:kb(home)};const rows=(await getReviewableContributionsList(db));const visible=[];for(const r of rows){if(await canReviewFolder(db,user.id,r[6]))visible.push(r);}const buttons=visible.slice(0,30).map(r=>[btn('📥 #'+r[0]+' '+String(r[3]).slice(0,32),'admin_contrib:'+r[0])]);buttons.push([btn('⬅️ إدارة المنصة','admin'),btn('🏠 الرئيسية','home')]);return {text:'📥 <b>مراجعة المساهمات</b>\n\nالعناصر القابلة للمراجعة: '+visible.length,reply_markup:kb(buttons)};}
export async function buildWorkerContributionReview(db,user,id){if(!(await hasPermission(db,user.id,'can_contributions')))return {text:'🔒 غير مصرح.',reply_markup:kb(home)};const r=await get(db,'SELECT id,user_id,user_name,folder_id,title,file_id,file_type,status,created_at,review_note,rejection_reason FROM contributions WHERE id=?',[Number(id)]);if(!r)return {text:'⚠️ المساهمة غير موجودة.',reply_markup:kb([[btn('⬅️ المساهمات','admin_pending')]])};if(!(await canReviewFolder(db,user.id,r[3])))return {text:'🚫 هذه المساهمة خارج نطاق مسؤوليتك.',reply_markup:kb([[btn('⬅️ المساهمات','admin_pending')]])};return {text:'📥 <b>مساهمة #'+r[0]+'</b>\n\n👤 '+String(r[2]||r[1])+'\n📄 '+String(r[4])+'\n🗂 Folder #'+r[3]+'\n🎞 '+r[6]+'\n📌 الحالة: '+r[7]+'\n🕒 '+r[8],reply_markup:kb([[btn('✅ قبول','admin_approve:'+r[0]),btn('❌ رفض','admin_reject:'+r[0])],[btn('⬅️ المساهمات','admin_pending'),btn('🏠 الرئيسية','home')]])};}
export async function reviewWorkerContribution(db,user,id,action){if(!(await hasPermission(db,user.id,'can_contributions')))return {ok:false,text:'🔒 غير مصرح.'};const row=await get(db,'SELECT folder_id FROM contributions WHERE id=?',[Number(id)]);if(!row||!(await canReviewFolder(db,user.id,row[0])))return {ok:false,text:'🚫 هذه المساهمة خارج نطاق مسؤوليتك.'};const result=action==='approve'?await approveContribution(db,Number(id),Number(user.id)):await rejectContribution(db,Number(id),Number(user.id),'رفض من لوحة Worker');return {ok:Boolean(result),text:result?(action==='approve'?'✅ تم قبول المساهمة ونشر المورد.':'✅ تم رفض المساهمة.'):'⚠️ تعذر تغيير حالة المساهمة.'};}
export async function buildWorkerAiAdmin(db,user){if(!(await hasPermission(db,user.id,'can_ai')))return {text:'🔒 غير مصرح.',reply_markup:kb(home)};const stats=await aiUsageStats(db,1),reg=await aiRegistryGetAll(db);const lines=['🤖 <b>AI Registry / Runtime</b>','', 'النماذج المسجلة: '+reg.length,''];for(const r of stats.slice(0,10))lines.push('• '+r[1]+' / '+r[2]+' — '+r[4]+' طلب · '+r[5]+' ناجح · avg '+(r[7]??'—')+'ms');return {text:lines.join('\n'),reply_markup:kb([[btn('🔄 تحديث','admin_ai')],[btn('⬅️ إدارة المنصة','admin'),btn('🏠 الرئيسية','home')]])};}
export async function buildWorkerAdmins(db,user){if(!(await hasPermission(db,user.id,'can_admins')))return {text:'🔒 غير مصرح.',reply_markup:kb(home)};const rows=await getAdminsFullRecords(db);const lines=['👥 <b>إدارة المشرفين</b>',''];for(const admin of rows)lines.push('• '+(admin.username?'@'+admin.username:admin.telegram_id)+' — '+(ROLE_LABELS[admin.role]??admin.role));const buttons=rows.map(r=>[btn((r.username?'@'+r.username:r.telegram_id)+' · '+(ROLE_LABELS[r.role]??r.role),'admin_user:'+r.telegram_id)]);buttons.push([btn('➕ إضافة مشرف','admin_add')]);buttons.push([btn('⬅️ إدارة المنصة','admin'),btn('🏠 الرئيسية','home')]);return {text:lines.join('\n'),reply_markup:kb(buttons)};}
export async function buildWorkerAdminUser(db,user,id){if(!(await hasPermission(db,user.id,'can_admins')))return {text:'🔒 غير مصرح.',reply_markup:kb(home)};const r=await getAdminRecord(db,id);if(!r)return {text:'⚠️ غير موجود.',reply_markup:kb([[btn('⬅️ المشرفون','admin_admins')]])};const scopes=await getAdminScopes(db,id);const rows=[];if(r.role!=='owner'){rows.push([btn('🛡 مشرف','admin_role:'+r.telegram_id+':admin'),btn('🔎 مراجع','admin_role:'+r.telegram_id+':reviewer')]);rows.push([btn('⛔ سحب الوصول','admin_role:'+r.telegram_id+':none')]);rows.push([btn('🔐 الصلاحيات','admin_perms:'+r.telegram_id)]);rows.push([btn('🧭 النطاق','admin_scopes:'+r.telegram_id)]);}rows.push([btn('⬅️ المشرفون','admin_admins')]);return {text:'👤 <b>'+String(r.username||r.telegram_id)+'</b>\n\n🆔 '+r.telegram_id+'\n👑 '+(ROLE_LABELS[r.role]??r.role)+'\n\n🔐 الصلاحيات: '+PERMISSION_KEYS.filter(k=>r.role==='owner'||r.permissions[k]).length+'/'+PERMISSION_KEYS.length+'\n🧭 النطاقات: '+scopes.length,reply_markup:kb(rows)};}
export async function buildWorkerAdminPermissions(db,user,id){if(!(await hasPermission(db,user.id,'can_admins')))return {text:'🔒 غير مصرح.',reply_markup:kb(home())};const r=await getAdminRecord(db,id);if(!r||r.role==='owner')return {text:'⚠️ لا يمكن تعديل صلاحيات هذا الحساب.',reply_markup:kb([[btn('⬅️ رجوع','admin_user:'+id)]])};const rows=PERMISSION_KEYS.map(k=>[btn((r.permissions[k]?'✅ ':'⛔ ')+(PERMISSION_LABELS[k]??k),'admin_perm:'+id+':'+k)]);rows.push([btn('⬅️ رجوع','admin_user:'+id)]);return {text:'🔐 <b>صلاحيات المشرف</b>\n\nاضغط على الصلاحية لمنحها أو سحبها.',reply_markup:kb(rows)};}
export async function toggleWorkerAdminPermission(db,user,id,key){if(!(await isOwner(db,user.id)))return {text:'🔒 المالك فقط.'};if(!PERMISSION_KEYS.includes(key))return {text:'⚠️ صلاحية غير معروفة.'};const r=await getAdminRecord(db,id);if(!r||r.role==='owner')return {text:'⚠️ لا يمكن تعديل هذا الحساب.'};const permissions={...r.permissions,[key]:!r.permissions[key]};await run(db,'UPDATE admins SET permissions=? WHERE telegram_id=?',[permissionsToString(permissions),Number(id)]);return {text:'✅ تم تحديث الصلاحية.'};}
export async function buildWorkerAdminScopes(db,user,id){if(!(await hasPermission(db,user.id,'can_admins')))return {text:'🔒 غير مصرح.',reply_markup:kb(home())};const r=await getAdminRecord(db,id);if(!r||r.role==='owner')return {text:'⚠️ لا يمكن تعديل نطاق هذا الحساب.',reply_markup:kb([[btn('⬅️ رجوع','admin_user:'+id)]])};const scopes=await getAdminScopes(db,id);const lines=['🧭 <b>نطاقات المشرف</b>',''];for(const s of scopes)lines.push('• '+s.scope_type+' #'+s.scope_id);return {text:lines.join('\n')+'\n\nلإضافة نطاق استخدم: /adminscope <telegram_id> <folder|topic|resource> <id>',reply_markup:kb([[btn('⬅️ رجوع','admin_user:'+id)]])};}
export async function applyWorkerAdminRole(db,user,target,role){if(!(await isOwner(db,user.id)))return {text:'🔒 المالك فقط.'};if(Number(target)===Number(user.id)||role==='owner')return {text:'⚠️ لا يمكن تطبيق هذا الدور.'};const ok=await setAdminRole(db,Number(target),role);return {text:ok?'✅ تم تحديث الدور.':'⚠️ تعذر تحديث الدور.'};}
export async function addWorkerAdmin(db,user,telegramId,username,role='admin'){if(!(await isOwner(db,user.id)))return {ok:false,text:'🔒 المالك فقط.'};const id=Number(telegramId);if(!Number.isSafeInteger(id)||id<=0||!['admin','reviewer'].includes(role))return {ok:false,text:'⚠️ بيانات المشرف غير صالحة.'};if(await getAdminRecord(db,id))return {ok:false,text:'⚠️ هذا الحساب موجود بالفعل.'};await run(db,'INSERT INTO admins(telegram_id,username,role,permissions) VALUES(?,?,?,?)',[id,username||null,role,permissionsToString(ROLE_PERMISSION_PRESETS[role])]);return {ok:true,text:'✅ تم إضافة المشرف.'};}

export async function buildWorkerRuntime(db,user){
 const id=Number(user.id);
 if(!(await isAdmin(db,id))) return {text:'🔒 غير مصرح.',reply_markup:kb(home)};
 const [folders,content,admins,audit,pending,news] = await Promise.all([
  get(db,'SELECT COUNT(*) FROM folders'),get(db,'SELECT COUNT(*) FROM content'),get(db,'SELECT COUNT(*) FROM admins'),
  get(db,'SELECT COUNT(*) FROM audit_log'),get(db,"SELECT COUNT(*) FROM contributions WHERE status='pending'"),get(db,"SELECT COUNT(*) FROM news WHERE status='published'"),
 ]);
 return {text:'📊 <b>حالة التشغيل</b>\n\n🗂 الأقسام: '+Number(folders?.[0]??0)+'\n📄 الموارد: '+Number(content?.[0]??0)+'\n👥 المشرفون: '+Number(admins?.[0]??0)+'\n📥 مساهمات بانتظار المراجعة: '+Number(pending?.[0]??0)+'\n📜 أحداث التدقيق: '+Number(audit?.[0]??0)+'\n📰 الأخبار المنشورة: '+Number(news?.[0]??0),reply_markup:kb([[btn('🤖 سجل الذكاء الاصطناعي','admin_ai')],[btn('⬅️ إدارة المنصة','admin'),btn('🏠 الرئيسية','home')]])};
}
