import { all, get, run } from '../db/d1/core.js';
import { hasPermission } from '../db/d1/admins.js';
import { adminHasScopes, folderInAdminScope, resourceInAdminScope, isTopicInAdminScope, newsInAdminScope } from '../db/d1/scopes.js';
import { getFolders, getFolderView, addFolder, updateFolderName, deleteFile, updateFileTitle, addContent } from '../db/d1/registry.js';
import { getTopics, getTopic, getTopicFolders, getTopicResourceCount } from '../db/d1/topics.js';
import { listNews, getNewsDetail, publishNews, deleteNews } from '../db/d1/news.js';
import { PLATFORM_SETTING_DEFAULTS, PLATFORM_SETTING_KEYS, PLATFORM_SETTING_LABELS } from '../constants.js';
const kb=rows=>({inline_keyboard:rows});const btn=(text,callback_data)=>({text,callback_data});const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');const home=()=>[[btn('🏠 الرئيسية','home')],[btn('⬅️ إدارة المنصة','admin')]];
export async function buildWorkerNotifications(db,user){
  if(!(await hasPermission(db,user.id,'can_notifications'))) return {text:'🔒 غير مصرح.',reply_markup:kb(home())};
  const rows=await getNotifications(db,10);
  const lines=['🔔 <b>الإشعارات والبث</b>','', 'إرسال إعلان عام إلى المستخدمين المسجلين.'];
  if(rows.length){
    lines.push('','📜 <b>آخر الإشعارات:</b>');
    for(const r of rows) lines.push('• '+String(r[2]||'إشعار')+' — '+r[6]+'/'+r[5]+' · '+String(r[7]||''));
  }
  return {text:lines.join('\n'),reply_markup:kb([[btn('📢 إرسال إشعار','admin_notify_send')],[btn('⬅️ أدوات الإدارة','admin_surfaces'),btn('🏠 الرئيسية','home')]])};
}
export async function sendWorkerNotification(db,user,bot,title,body){
  if(!(await hasPermission(db,user.id,'can_notifications'))) return {text:'🔒 غير مصرح.'};
  const clean=String(body??'').trim().slice(0,3000), cleanTitle=String(title??'').trim().slice(0,200);
  if(!clean) return {text:'⚠️ نص الإشعار فارغ.'};
  const users=await all(db,'SELECT telegram_id FROM users ORDER BY telegram_id ASC',[]);
  let delivered=0;
  for(const row of users){
    try{ await bot.sendMessage(row[0], '🔔 <b>'+esc(cleanTitle||'إشعار من إدارة المنصة')+'</b>\n\n'+esc(clean), {parse_mode:'HTML'}); delivered++; }catch{}
  }
  await recordNotification(db,user.id,cleanTitle,clean,'all',users.length,delivered);
  await addAuditEntry(db,user.id,'admin','notification_broadcast','notification',null,JSON.stringify({recipients:users.length,delivered}));
  return {text:'✅ <b>تم إرسال الإشعار.</b>\n\nالمستلمون: '+users.length+'\nتم التسليم: '+delivered};
}
export async function buildWorkerAdminSurfaces(db,user){const id=Number(user.id),rows=[];if(await hasPermission(db,id,'can_folders'))rows.push([btn('📁 إدارة الأقسام','admin_folders')]);if(await hasPermission(db,id,'can_content'))rows.push([btn('📄 إدارة الموارد','admin_content')]);if(await hasPermission(db,id,'can_messages'))rows.push([btn('📬 رسائل الطلاب','admin_messages')]);if(await hasPermission(db,id,'can_news'))rows.push([btn('📰 إدارة الأخبار','admin_news')]);if(await hasPermission(db,id,'can_topics'))rows.push([btn('🧭 إدارة المواضيع','admin_topics')]);if(await hasPermission(db,id,'can_visibility'))rows.push([btn('👁 إظهار/إخفاء الأقسام','admin_visibility')]);if(await hasPermission(db,id,'can_settings'))rows.push([btn('⚙️ إعدادات المنصة','admin_settings')]);rows.push([btn('⬅️ إدارة المنصة','admin'),btn('🏠 الرئيسية','home')]);return{text:'🧰 <b>أدوات إدارة المنصة</b>\n\nاختر القسم الذي تريد إدارته:',reply_markup:kb(rows)};}
export async function buildWorkerFolders(db,user,parentId=0){if(!(await hasPermission(db,user.id,'can_folders')))return{text:'🔒 غير مصرح.',reply_markup:kb(home())};const scoped=await adminHasScopes(db,user.id);if(scoped&&parentId&&!(await folderInAdminScope(db,user.id,parentId)))return{text:'🚫 هذا القسم خارج نطاق مسؤوليتك.',reply_markup:kb(home())};let rows=await getFolders(db,parentId||null);if(scoped){const allowed=await Promise.all(rows.map(r=>folderInAdminScope(db,user.id,r[0])));rows=rows.filter((_,i)=>allowed[i]);}const buttons=rows.map(r=>[btn('📁 '+String(r[1]).slice(0,36),'admin_folder:'+r[0])]);buttons.push([btn('➕ قسم جديد','admin_folder_create:'+Number(parentId||0))]);if(parentId)buttons.push([btn('⬅️ رجوع','admin_folders:0')]);buttons.push([btn('🏠 الرئيسية','home')]);return{text:'📁 <b>إدارة الأقسام</b>\n\n'+(rows.length?'اختر قسماً:':'لا توجد أقسام في هذا المستوى.'),reply_markup:kb(buttons)};}
export async function buildWorkerFolderAdmin(db,user,id){if(!(await hasPermission(db,user.id,'can_folders')))return{text:'🔒 غير مصرح.',reply_markup:kb(home())};if(await adminHasScopes(db,user.id)&&!(await folderInAdminScope(db,user.id,Number(id))))return{text:'🚫 هذا القسم خارج نطاق مسؤوليتك.',reply_markup:kb(home())};const view=await getFolderView(db,Number(id));if(!view?.folder)return{text:'⚠️ القسم غير موجود.',reply_markup:kb(home())};const f=view.folder;return{text:'📁 <b>'+esc(f[1])+'</b>\n\nالنوع: '+esc(f[2]??'general')+'\nالمساهمات: '+(f[3]?'مفعلة':'غير مفعلة')+'\nالعناصر: '+view.files.length+'\nالأقسام الفرعية: '+view.children.length,reply_markup:kb([[btn('➕ قسم فرعي','admin_folder_create:'+id)],[btn('✏️ إعادة تسمية','admin_folder_rename:'+id)],[btn('🗑 حذف القسم','admin_folder_delete:'+id)],[btn('📂 فتح','admin_folders:'+id)],[btn('⬅️ الأقسام','admin_folders:0'),btn('🏠 الرئيسية','home')]])};}
export async function createFolderFromText(db,user,parentId,name){if(!(await hasPermission(db,user.id,'can_folders')))return{text:'🔒 غير مصرح.'};if(await adminHasScopes(db,user.id)&&(!Number(parentId)||!(await folderInAdminScope(db,user.id,Number(parentId)))))return{text:'🚫 لا يمكنك إنشاء قسم خارج نطاق مسؤوليتك.'};const n=String(name).trim().slice(0,120);if(!n)return{text:'⚠️ الاسم فارغ.'};await addFolder(db,Number(parentId)||null,n,'general',0);return{text:'✅ تم إنشاء القسم.',ok:true};}
export async function renameFolderFromText(db,user,id,name){if(!(await hasPermission(db,user.id,'can_folders')))return{text:'🔒 غير مصرح.'};if(await adminHasScopes(db,user.id)&&!(await folderInAdminScope(db,user.id,Number(id))))return{text:'🚫 هذا القسم خارج نطاق مسؤوليتك.'};const n=String(name).trim().slice(0,120);if(!n)return{text:'⚠️ الاسم فارغ.'};await updateFolderName(db,Number(id),n);return{text:'✅ تم تغيير اسم القسم.',ok:true};}
export async function deleteFolder(db,user,id){if(!(await hasPermission(db,user.id,'can_folders')))return{text:'🔒 غير مصرح.'};if(await adminHasScopes(db,user.id)&&!(await folderInAdminScope(db,user.id,Number(id))))return{text:'🚫 هذا القسم خارج نطاق مسؤوليتك.'};const children=await get(db,'SELECT COUNT(*) FROM folders WHERE parent_id=?',[Number(id)]),files=await get(db,'SELECT COUNT(*) FROM content WHERE folder_id=?',[Number(id)]);if(Number(children?.[0]??0)||Number(files?.[0]??0))return{text:'⚠️ لا يمكن حذف قسم غير فارغ. انقل محتواه أولاً.'};return{ok:(await run(db,'DELETE FROM folders WHERE id=?',[Number(id)])).changes>0,text:'🗑 تم حذف القسم.'};}
export async function buildWorkerContentAdmin(db,user,folderId=0){if(!(await hasPermission(db,user.id,'can_content')))return{text:'🔒 غير مصرح.',reply_markup:kb(home())};const scoped=await adminHasScopes(db,user.id);if(scoped&&folderId&&!(await folderInAdminScope(db,user.id,Number(folderId))))return{text:'🚫 هذا القسم خارج نطاق مسؤوليتك.',reply_markup:kb(home())};let folders=await getFolders(db,folderId||null);if(scoped){const allowed=await Promise.all(folders.map(r=>folderInAdminScope(db,user.id,r[0])));folders=folders.filter((_,i)=>allowed[i]);}const view=folderId?await getFolderView(db,folderId):null,buttons=folders.map(r=>[btn('📁 '+String(r[1]).slice(0,34),'admin_content:'+r[0])]);for(const f of view?.files??[])buttons.push([btn('📄 '+String(f[1]).slice(0,34),'admin_file:'+f[0])]);if(folderId)buttons.push([btn('➕ رفع مورد','admin_upload:'+folderId)]);buttons.push([btn('⬅️ أدوات الإدارة','admin_surfaces'),btn('🏠 الرئيسية','home')]);return{text:'📄 <b>إدارة الموارد</b>\n\n'+(folderId?'المجلد الحالي: '+folderId:'اختر مجلداً لإدارة موارده.'),reply_markup:kb(buttons)};}
export async function handleWorkerAdminMedia(db,user,message,folderId){if(!(await hasPermission(db,user.id,'can_content')))return{text:'🔒 غير مصرح.'};if(await adminHasScopes(db,user.id)&&!(await folderInAdminScope(db,user.id,Number(folderId))))return{text:'🚫 هذا القسم خارج نطاق مسؤوليتك.'};let media=null;if(message?.document)media=['document',message.document.file_id];else if(message?.photo?.length)media=['photo',message.photo.at(-1).file_id];else if(message?.video)media=['video',message.video.file_id];else if(message?.audio)media=['audio',message.audio.file_id];if(!media)return{text:'⚠️ أرسل مستنداً أو صورة أو فيديو أو صوتاً.'};const title=String(message?.caption??'').trim();if(!title)return{text:'⚠️ اكتب عنوان المورد في caption ثم أرسله مرة أخرى.'};await addContent(db,Number(folderId),title,media[1],media[0],'direct',null,Number(user.id));return{text:'✅ تم رفع المورد وإضافته إلى المكتبة.'};}
export async function buildWorkerFileAdmin(db,user,id){if(!(await hasPermission(db,user.id,'can_content')))return{text:'🔒 غير مصرح.',reply_markup:kb(home())};if(await adminHasScopes(db,user.id)&&!(await resourceInAdminScope(db,user.id,Number(id))))return{text:'🚫 هذا المورد خارج نطاق مسؤوليتك.',reply_markup:kb(home())};const r=await get(db,'SELECT id,folder_id,title,file_type,created_at FROM content WHERE id=?',[Number(id)]);if(!r)return{text:'⚠️ المورد غير موجود.',reply_markup:kb(home())};return{text:'📄 <b>'+esc(r[2])+'</b>\n\nالنوع: '+esc(r[3])+'\nتاريخ الإضافة: '+esc(r[4]),reply_markup:kb([[btn('✏️ إعادة تسمية','admin_file_rename:'+r[0])],[btn('🗑 حذف','admin_file_delete:'+r[0])],[btn('⬅️ الموارد','admin_content:'+r[1]),btn('🏠 الرئيسية','home')]])};}
export async function renameFileFromText(db,user,id,title){if(!(await hasPermission(db,user.id,'can_content')))return{text:'🔒 غير مصرح.'};if(await adminHasScopes(db,user.id)&&!(await resourceInAdminScope(db,user.id,Number(id))))return{text:'🚫 هذا المورد خارج نطاق مسؤوليتك.'};const t=String(title).trim().slice(0,200);if(!t)return{text:'⚠️ العنوان فارغ.'};await updateFileTitle(db,Number(id),t);return{text:'✅ تم تغيير عنوان المورد.',ok:true};}
export async function deleteFileWorker(db,user,id){if(!(await hasPermission(db,user.id,'can_content')))return{text:'🔒 غير مصرح.'};if(await adminHasScopes(db,user.id)&&!(await resourceInAdminScope(db,user.id,Number(id))))return{text:'🚫 هذا المورد خارج نطاق مسؤوليتك.'};return{ok:(await deleteFile(db,Number(id))).changes>0,text:'🗑 تم حذف المورد.'};}
export async function buildWorkerMessages(db,user){if(!(await hasPermission(db,user.id,'can_messages')))return{text:'🔒 غير مصرح.',reply_markup:kb(home())};const rows=await all(db,"SELECT id,user_id,user_name,category,status,created_at,body FROM messages WHERE status IN ('NEW','IN_REVIEW') ORDER BY created_at DESC LIMIT 30",[]),buttons=rows.map(r=>[btn('📬 #'+r[0]+' '+String(r[2]||r[1]).slice(0,28),'admin_msg:'+r[0])]);buttons.push([btn('⬅️ أدوات الإدارة','admin_surfaces'),btn('🏠 الرئيسية','home')]);return{text:'📬 <b>رسائل الطلاب</b>\n\nرسائل مفتوحة: '+rows.length,reply_markup:kb(buttons)};}
export async function buildWorkerMessage(db,user,id){if(!(await hasPermission(db,user.id,'can_messages')))return{text:'🔒 غير مصرح.',reply_markup:kb(home())};const r=await get(db,'SELECT id,user_id,user_name,category,status,body,admin_reply,created_at FROM messages WHERE id=?',[Number(id)]);if(!r)return{text:'⚠️ الرسالة غير موجودة.',reply_markup:kb(home())};return{text:'📬 <b>رسالة #'+r[0]+'</b>\n\n👤 '+esc(r[2]||r[1])+'\n🏷 '+esc(r[3])+'\n📌 '+esc(r[4])+'\n\n'+esc(r[5])+(r[6]?'\n\n↩️ الرد: '+esc(r[6]):''),reply_markup:kb([[btn('↩️ رد','admin_msg_reply:'+r[0])],[btn('✅ إغلاق','admin_msg_close:'+r[0])],[btn('⬅️ الرسائل','admin_messages'),btn('🏠 الرئيسية','home')]])};}
export async function closeWorkerMessage(db,user,id){if(!(await hasPermission(db,user.id,'can_messages')))return{text:'🔒 غير مصرح.'};await run(db,"UPDATE messages SET status='CLOSED',reviewed_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",[Number(user.id),Number(id)]);return{text:'✅ تم إغلاق الرسالة.'};}
export async function replyWorkerMessage(db,user,id,reply,bot){if(!(await hasPermission(db,user.id,'can_messages')))return{text:'🔒 غير مصرح.'};const r=await get(db,'SELECT user_id FROM messages WHERE id=?',[Number(id)]);if(!r)return{text:'⚠️ الرسالة غير موجودة.'};const body=String(reply).trim().slice(0,1500);if(!body)return{text:'⚠️ الرد فارغ.'};await bot.sendMessage(r[0],body);await run(db,"UPDATE messages SET status='REPLIED',admin_reply=?,reviewed_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",[body,Number(user.id),Number(id)]);return{text:'✅ تم إرسال الرد.'};}
export async function buildWorkerTopicsAdmin(db,user){if(!(await hasPermission(db,user.id,'can_topics')))return{text:'🔒 غير مصرح.',reply_markup:kb(home())};const scoped=await adminHasScopes(db,user.id);let topics=await getTopics(db,false);if(scoped)topics=topics.filter(t=>isTopicInAdminScope(db,user.id,t[0]));const buttons=topics.map(t=>[btn((t[3]||'🧭')+' '+String(t[1]).slice(0,34),'admin_topic:'+t[0])]);buttons.push([btn('⬅️ أدوات الإدارة','admin_surfaces'),btn('🏠 الرئيسية','home')]);return{text:'🧭 <b>إدارة المواضيع</b>\n\n'+(topics.length?'اختر موضوعاً:':'لا توجد مواضيع.'),reply_markup:kb(buttons)};}
export async function buildWorkerTopicAdmin(db,user,id){if(!(await hasPermission(db,user.id,'can_topics')))return{text:'🔒 غير مصرح.',reply_markup:kb(home())};if(await adminHasScopes(db,user.id)&&!(await isTopicInAdminScope(db,user.id,Number(id))))return{text:'🚫 هذا الموضوع خارج نطاق مسؤوليتك.',reply_markup:kb(home())};const t=await getTopic(db,Number(id));if(!t)return{text:'⚠️ الموضوع غير موجود.',reply_markup:kb(home())};const folders=await getTopicFolders(db,Number(id)),count=await getTopicResourceCount(db,Number(id));return{text:(t[3]||'🧭')+' <b>'+esc(t[1])+'</b>\n\n'+esc(t[2]||'')+'\n\n📚 الموارد: '+count+'\n📂 الأقسام المرتبطة: '+folders.length,reply_markup:kb([[btn('🔄 تفعيل/إيقاف','admin_topic_toggle:'+id)],[btn('⬅️ المواضيع','admin_topics'),btn('🏠 الرئيسية','home')]])};}
export async function toggleWorkerTopic(db,user,id){if(!(await hasPermission(db,user.id,'can_topics')))return{text:'🔒 غير مصرح.'};if(await adminHasScopes(db,user.id)&&!(await isTopicInAdminScope(db,user.id,Number(id))))return{text:'🚫 هذا الموضوع خارج نطاق مسؤوليتك.'};const r=await get(db,'SELECT active FROM topics WHERE id=?',[Number(id)]);if(!r)return{text:'⚠️ غير موجود.'};await run(db,'UPDATE topics SET active=? WHERE id=?',[r[0]?0:1,Number(id)]);return{text:r[0]?'⛔ تم إيقاف الموضوع.':'✅ تم تفعيل الموضوع.'};}
export async function buildWorkerSettings(db,user){if(!(await hasPermission(db,user.id,'can_settings')))return{text:'🔒 غير مصرح.',reply_markup:kb(home())};const rows=await Promise.all(PLATFORM_SETTING_KEYS.map(async k=>[k,(await get(db,'SELECT value FROM settings WHERE key=?',[k]))?.[0]??PLATFORM_SETTING_DEFAULTS[k]??'']));const buttons=rows.map(([k])=>[btn('⚙️ '+k,'admin_setting:'+k)]);buttons.push([btn('⬅️ أدوات الإدارة','admin_surfaces'),btn('🏠 الرئيسية','home')]);return{text:'⚙️ <b>إعدادات المنصة</b>\n\n'+rows.map(([k,v])=>'• <b>'+esc(k)+'</b>: '+esc(String(v).slice(0,100))).join('\n'),reply_markup:kb(buttons)};}
export async function settingPrompt(db,user,key){if(!(await hasPermission(db,user.id,'can_settings')))return{text:'🔒 غير مصرح.'};return{text:'✏️ <b>'+esc(PLATFORM_SETTING_LABELS[key]??key)+'</b>\n\nأرسل القيمة الجديدة للإعداد الآن.\n\nلإلغاء العملية أرسل /cancel.',ok:true};}
export async function saveSetting(db,user,key,value){if(!(await hasPermission(db,user.id,'can_settings'))||!PLATFORM_SETTING_KEYS.includes(key))return{text:'🔒 غير مصرح.'};const v=String(value).trim().slice(0,1500);await run(db,'INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value',[key,v]);return{text:'✅ تم تحديث الإعداد.',ok:true};}
export async function buildWorkerNewsAdmin(db,user){if(!(await hasPermission(db,user.id,'can_news')))return{text:'🔒 غير مصرح.',reply_markup:kb(home())};let rows=await listNews(db,{status:'draft',limit:50,offset:0});if(await adminHasScopes(db,user.id)){const allowed=await Promise.all(rows.map(r=>newsInAdminScope(db,user.id,r.id)));rows=rows.filter((_,i)=>allowed[i]);}const buttons=rows.map(r=>[btn('📰 #'+r.id+' '+String(r.title).slice(0,32),'admin_news_item:'+r.id)]);buttons.push([btn('⬅️ أدوات الإدارة','admin_surfaces'),btn('🏠 الرئيسية','home')]);return{text:'📰 <b>إدارة الأخبار</b>\n\nمسودات: '+rows.length,reply_markup:kb(buttons)};}
export async function buildWorkerNewsItem(db,user,id){if(!(await hasPermission(db,user.id,'can_news')))return{text:'🔒 غير مصرح.',reply_markup:kb(home())};if(await adminHasScopes(db,user.id)&&!(await newsInAdminScope(db,user.id,Number(id))))return{text:'🚫 هذا الخبر خارج نطاق مسؤوليتك.',reply_markup:kb(home())};const n=await getNewsDetail(db,Number(id));if(!n)return{text:'⚠️ الخبر غير موجود.',reply_markup:kb(home())};return{text:'📰 <b>'+esc(n.title)+'</b>\n\n'+esc(n.body||''),reply_markup:kb([[btn('📢 نشر','admin_news_publish:'+id)],[btn('🗑 حذف','admin_news_delete:'+id)],[btn('⬅️ الأخبار','admin_news')]])};}
export async function publishWorkerNews(db,user,id){if(!(await hasPermission(db,user.id,'can_news')))return{text:'🔒 غير مصرح.'};if(await adminHasScopes(db,user.id)&&!(await newsInAdminScope(db,user.id,Number(id))))return{text:'🚫 هذا الخبر خارج نطاق مسؤوليتك.'};await publishNews(db,Number(id));return{text:'📢 تم نشر الخبر.'};}
export async function deleteWorkerNews(db,user,id){if(!(await hasPermission(db,user.id,'can_news')))return{text:'🔒 غير مصرح.'};if(await adminHasScopes(db,user.id)&&!(await newsInAdminScope(db,user.id,Number(id))))return{text:'🚫 هذا الخبر خارج نطاق مسؤوليتك.'};await deleteNews(db,Number(id));return{text:'🗑 تم حذف الخبر.'};}
export async function buildWorkerVisibility(db,user){if(!(await hasPermission(db,user.id,'can_visibility')))return{text:'🔒 غير مصرح.',reply_markup:kb(home())};const hidden=new Set(String((await get(db,'SELECT value FROM settings WHERE key=?',['hidden_features']))?.[0]??'').split(',').map(x=>x.trim()).filter(Boolean));const features=['resources','assistant','contributions','my_contributions','account','topics','news','language','contact','about'];const rows=features.map(f=>[btn((hidden.has(f)?'🙈':'👁️')+' '+f,'admin_visibility_toggle:'+f)]);rows.push([btn('⬅️ أدوات الإدارة','admin_surfaces'),btn('🏠 الرئيسية','home')]);return{text:'👁 <b>إظهار/إخفاء أقسام الطلاب</b>\n\nاضغط لتبديل الحالة.',reply_markup:kb(rows)};}
export async function toggleWorkerVisibility(db,user,feature){if(!(await hasPermission(db,user.id,'can_visibility')))return{text:'🔒 غير مصرح.'};const row=await get(db,'SELECT value FROM settings WHERE key=?',['hidden_features']),hidden=new Set(String(row?.[0]??'').split(',').map(x=>x.trim()).filter(Boolean));if(hidden.has(feature))hidden.delete(feature);else hidden.add(feature);await run(db,'INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value',['hidden_features',[...hidden].join(',')]);return{text:'✅ تم تحديث ظهور القسم.'};}
