import { get, all } from '../db/d1/core.js';
import { hasPermission, isAdmin, isOwner, getAdminsFullRecords, setAdminRole } from '../db/d1/admins.js';
import { getPendingContributionsCount, getReviewableContributionsList, approveContribution, rejectContribution } from '../db/d1/contributions.js';
import { aiUsageStats, aiRegistryGetAll } from '../db/d1/aiRegistry.js';
import { adminHasScopes, folderInAdminScope } from '../db/d1/scopes.js';
const kb=rows=>({inline_keyboard:rows});const btn=(text,callback_data)=>({text,callback_data});
const home=[[btn('🏠 الرئيسية','home')]];
export async function buildWorkerAdmin(db,user){const id=Number(user.id);if(!(await isAdmin(db,id)))return {text:'🔒 هذه المنطقة مخصصة للمشرفين المعتمدين فقط.',reply_markup:kb(home)};const rows=[];const pending=await getPendingContributionsCount(db);if(await hasPermission(db,id,'can_contributions'))rows.push([btn('📥 مراجعة المساهمات'+(pending?' ('+pending+')':''),'admin_pending')]);if(await hasPermission(db,id,'can_ai'))rows.push([btn('🤖 سجل الذكاء الاصطناعي','admin_ai')]);if(await hasPermission(db,id,'can_admins'))rows.push([btn('👥 إدارة المشرفين','admin_admins')]);rows.push([btn('📊 حالة التشغيل','admin_runtime'),btn('🏠 الرئيسية','home')]);return {text:'🛠 <b>إدارة المنصة</b>\n\nاختر الإجراء الذي تريد تنفيذه:',reply_markup:kb(rows)};}
async function canReviewFolder(db,userId,folderId){if(!(await hasPermission(db,userId,'can_contributions')))return false;return !(await adminHasScopes(db,userId)) || await folderInAdminScope(db,userId,folderId);}
export async function buildWorkerPending(db,user){if(!(await hasPermission(db,user.id,'can_contributions')))return {text:'🔒 غير مصرح.',reply_markup:kb(home)};const rows=(await getReviewableContributionsList(db)).filter(r=>true);const visible=[];for(const r of rows){if(await canReviewFolder(db,user.id,r[6]))visible.push(r);}const buttons=visible.slice(0,30).map(r=>[btn('📥 #'+r[0]+' '+String(r[3]).slice(0,32),'admin_contrib:'+r[0])]);buttons.push([btn('⬅️ إدارة المنصة','admin'),btn('🏠 الرئيسية','home')]);return {text:'📥 <b>مراجعة المساهمات</b>\n\nالعناصر القابلة للمراجعة: '+visible.length,reply_markup:kb(buttons)};}
export async function buildWorkerContributionReview(db,user,id){if(!(await hasPermission(db,user.id,'can_contributions')))return {text:'🔒 غير مصرح.',reply_markup:kb(home)};const r=await get(db,'SELECT id,user_id,user_name,folder_id,title,file_id,file_type,status,created_at,review_note,rejection_reason FROM contributions WHERE id=?',[Number(id)]);if(!r)return {text:'⚠️ المساهمة غير موجودة.',reply_markup:kb([[btn('⬅️ المساهمات','admin_pending')]])};if(!(await canReviewFolder(db,user.id,r[3])))return {text:'🚫 هذه المساهمة خارج نطاق مسؤوليتك.',reply_markup:kb([[btn('⬅️ المساهمات','admin_pending')]])};return {text:'📥 <b>مساهمة #'+r[0]+'</b>\n\n👤 '+String(r[2]||r[1])+'\n📄 '+String(r[4])+'\n🗂 Folder #'+r[3]+'\n🎞 '+r[6]+'\n📌 الحالة: '+r[7]+'\n🕒 '+r[8],reply_markup:kb([[btn('✅ قبول','admin_approve:'+r[0]),btn('❌ رفض','admin_reject:'+r[0])],[btn('⬅️ المساهمات','admin_pending'),btn('🏠 الرئيسية','home')]])};}
export async function reviewWorkerContribution(db,user,id,action){if(!(await hasPermission(db,user.id,'can_contributions')))return {ok:false,text:'🔒 غير مصرح.'};const row=await get(db,'SELECT folder_id FROM contributions WHERE id=?',[Number(id)]);if(!row||!(await canReviewFolder(db,user.id,row[0])))return {ok:false,text:'🚫 هذه المساهمة خارج نطاق مسؤوليتك.'};const result=action==='approve'?await approveContribution(db,Number(id),Number(user.id)):await rejectContribution(db,Number(id),Number(user.id),'رفض من لوحة Worker');return {ok:Boolean(result),text:result?(action==='approve'?'✅ تم قبول المساهمة ونشر المورد.':'✅ تم رفض المساهمة.'):'⚠️ تعذر تغيير حالة المساهمة.'};}
export async function buildWorkerAiAdmin(db,user){if(!(await hasPermission(db,user.id,'can_ai')))return {text:'🔒 غير مصرح.',reply_markup:kb(home)};const stats=await aiUsageStats(db,1),reg=await aiRegistryGetAll(db);const lines=['🤖 <b>AI Registry / Runtime</b>','', 'النماذج المسجلة: '+reg.length,''];for(const r of stats.slice(0,10))lines.push('• '+r[1]+' / '+r[2]+' — '+r[4]+' طلب · '+r[5]+' ناجح · avg '+(r[7]??'—')+'ms');return {text:lines.join('\n'),reply_markup:kb([[btn('🔄 تحديث','admin_ai')],[btn('⬅️ إدارة المنصة','admin'),btn('🏠 الرئيسية','home')]])};}
export async function buildWorkerAdmins(db,user){if(!(await hasPermission(db,user.id,'can_admins')))return {text:'🔒 غير مصرح.',reply_markup:kb(home)};const rows=await getAdminsFullRecords(db);const lines=['👥 <b>إدارة المشرفين</b>',''];for(const r of rows)lines.push('• '+(r.username?'@'+r.username:r.telegram_id)+' — '+r.role);const buttons=rows.map(r=>[btn((r.username?'@'+r.username:r.telegram_id)+' · '+r.role,'admin_user:'+r.telegram_id)]);buttons.push([btn('⬅️ إدارة المنصة','admin'),btn('🏠 الرئيسية','home')]);return {text:lines.join('\n'),reply_markup:kb(buttons)};}
export async function buildWorkerAdminUser(db,user,id){if(!(await hasPermission(db,user.id,'can_admins')))return {text:'🔒 غير مصرح.',reply_markup:kb(home)};const r=await get(db,'SELECT telegram_id,username,role FROM admins WHERE telegram_id=?',[Number(id)]);if(!r)return {text:'⚠️ غير موجود.',reply_markup:kb([[btn('⬅️ المشرفون','admin_admins')]])};return {text:'👤 <b>'+String(r[1]||r[0])+'</b>\n\n🆔 '+r[0]+'\n👑 '+r[2],reply_markup:kb([[btn('🛡 مشرف','admin_role:'+r[0]+':admin'),btn('🔎 مراجع','admin_role:'+r[0]+':reviewer')],[btn('⛔ سحب الوصول','admin_role:'+r[0]+':none')],[btn('⬅️ المشرفون','admin_admins')]])};}
export async function applyWorkerAdminRole(db,user,target,role){if(!(await isOwner(db,user.id)))return {text:'🔒 المالك فقط.'};const ok=await setAdminRole(db,Number(target),role);return {text:ok?'✅ تم تحديث الدور.':'⚠️ تعذر تحديث الدور.'};}
