import { all, get, run } from './core.js';
import { PERMISSION_KEYS, ROLE_ASSIGNABLE, ROLE_PERMISSION_PRESETS, defaultPermissions, permissionsFromString, permissionsToString } from '../../constants.js';
export async function getAdminRecord(db,id){const r=await get(db,'SELECT telegram_id,username,added_at,role,permissions FROM admins WHERE telegram_id=?',[Number(id)]);if(!r)return null;return {telegram_id:r[0],username:r[1],added_at:r[2],role:r[3]||'admin',permissions:permissionsFromString(r[4])};}
export async function isAdmin(db,id){const r=await get(db,"SELECT role FROM admins WHERE telegram_id=? AND (role IS NULL OR role!='none')",[Number(id)]);return Boolean(r);}
export async function isOwner(db,id){const r=await get(db,"SELECT role FROM admins WHERE telegram_id=? AND role='owner'",[Number(id)]);return Boolean(r);}
export async function hasPermission(db,id,key){if(!PERMISSION_KEYS.includes(key))return false;const r=await get(db,'SELECT role,permissions FROM admins WHERE telegram_id=?',[Number(id)]);if(!r||r[0]==='none')return false;if(r[0]==='owner')return true;return Boolean(permissionsFromString(r[1])[key]);}
export async function getAdminsFullRecords(db){const rows=await all(db,'SELECT telegram_id,username,added_at,role,permissions FROM admins ORDER BY added_at ASC');return rows.map(r=>({telegram_id:r[0],username:r[1],added_at:r[2],role:r[3]||'admin',permissions:permissionsFromString(r[4])}));}
export async function ensureConfiguredAdmin(db,id,username=null){if(!id||Number(id)<=0)return false;const existing=await get(db,'SELECT role FROM admins WHERE telegram_id=?',[Number(id)]);if(!existing){await run(db,'INSERT INTO admins(telegram_id,username,role,permissions) VALUES(?,?,?,?)',[Number(id),username,'owner',permissionsToString(defaultPermissions())]);return true;}await run(db,'UPDATE admins SET username=? WHERE telegram_id=?',[username,Number(id)]);if(!(await isOwner(db,id))){await run(db,"UPDATE admins SET role='admin' WHERE role='owner' AND telegram_id!=?",[Number(id)]);await run(db,"UPDATE admins SET role='owner',permissions=? WHERE telegram_id=?",[permissionsToString(defaultPermissions()),Number(id)]);}return true;}
export async function setAdminRole(db,id,role){if(!ROLE_ASSIGNABLE.includes(role))return false;if(role!=='owner'&&(await isOwner(db,id)))return false;return (await run(db,'UPDATE admins SET role=?,permissions=? WHERE telegram_id=?',[role,permissionsToString(ROLE_PERMISSION_PRESETS[role]),Number(id)])).changes>0;}
